version: '2'
services:
  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Elasticsearch 6.x settings
      - discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3
      - discovery.zen.minimum_master_nodes=2
      # Elasticsearch 7.x settings
      #- discovery.seed_hosts=elasticsearch2,elasticsearch3
      #- cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata_upgrade1:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - esnet

  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Elasticsearch 6.x settings
      - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3
      - discovery.zen.minimum_master_nodes=2
      # Elasticsearch 7.x settings
      #- discovery.seed_hosts=elasticsearch1,elasticsearch3
      #- cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata_upgrade2:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - esnet

  elasticsearch3:
    container_name: elasticsearch3
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Elasticsearch 6.x settings
      - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2
      - discovery.zen.minimum_master_nodes=2
      # Elasticsearch 7.x settings
      #- discovery.seed_hosts=elasticsearch1,elasticsearch2
      #- cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata_upgrade3:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - esnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    links:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
    networks:
      - esnet

volumes:
  esdata_upgrade1:
    driver: local
  esdata_upgrade2:
    driver: local
  esdata_upgrade3:
    driver: local

networks:
  esnet:
