---
version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    links:
      - elasticsearch
    ports:
      - 5601:5601
    networks: ['stack']
    depends_on: ['elasticsearch']

  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log.json:/usr/local/log/log.json:ro
      - ./template.json:/usr/local/filebeat/template.json
    # Customize the template, activate the trial, and then run Filebeat
    command: >
      bash -c "curl -XPUT 'http://elasticsearch:9200/_template/filebeat' -d @/usr/local/filebeat/template.json -H 'Content-Type:application/json' &&
      curl -XPOST 'http://elasticsearch:9200/_xpack/license/start_trial?acknowledge=true' &&
      filebeat -e"
    restart: on-failure
    networks: ['stack']
    depends_on: ['kibana']

volumes:
  esdata1:
    driver: local
networks:
  stack: {}
