filebeat.inputs:
- type: log
  paths:
   - /usr/local/log/log.json
  json.keys_under_root: true
  json.overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  bulk_max_size: 5000

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
  template:
    settings.index:
      number_of_replicas: 0
      refresh_interval: -1
